site_name: MindEase Documentation
site_description: MindEase – Mood Tracking & Therapy Booking System Documentation
site_url: https://riddhima-gkmit.github.io/mindease-documentation/
repo_url: https://github.com/riddhima-gkmit/mindease-documentation/
repo_name: riddhima-gkmit.github.io/mindease-documentation
site_author: Riddhima Kushwah
copyright: "© 2025 MindEase. All rights reserved."

theme:
  name: material
  logo: assets/images/mindease-logo.png
  favicon: assets/favicon.png
  language: en
  features:
    - navigation.tabs           # Top-level tabs (Overview, Use Case)
    - navigation.sections       # Sectioned side navigation
    - navigation.top            # ‘Back to top’ button
    - navigation.footer         # Prev/Next buttons at page bottom
    - search.suggest
    - search.highlight
    - content.code.copy         # Copy button on code blocks
    - content.tabs.link         # Tabbed content linkage
    - toc.integrate             # Integrated ToC on pages
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides          # Enables custom footer partial

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username
      name: GitHub
  version:
    provider: mkdocs
  generator: false

plugins:
  - search
  - glightbox
  - mermaid2
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
  - footnotes
  - abbr
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.keys

extra_css:
  - theme/extra.css

extra_javascript:
  - theme/extra.js

nav:
  - Home: index.md
  - Functional Docs: functional-docs.md
  - Use Cases: use-cases.md
  - Technical Docs:
      - Tech Stack: technical/tech-stack.md
      - Architecture: technical/architecture.md
      - Data Flow: technical/data-flow.md
      - Schema Design: technical/schema-design.md
      - Authentication: technical/authentication.md
      - API Design: technical/api-design.md
  - Edge Cases & Error Handling: edge-cases.md
  - Future Enhancements: future.md
  - Test Plan: test-plan.md
  - CI/CD Pipeline and Deployment Flow: ci-cd-pipeline-and-deployment-flow.md